# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  testjhipster2-postgresql:
    image: postgres:15
    volumes:
      - ~/volumes/jhipster/testjhipster2/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testjhipster2
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5434:5434
