# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  testjhipster2-sonar:
    image: sonarqube:10.0.0-enterprise
    depends_on:
      - db_JH
    environment:
      SONAR_JDBC_USERNAME: sonarjhipster
      SONAR_JDBC_PASSWORD: sonarjhipster
      SONAR_JDBC_URL: jdbc:postgresql://docker-db_JH-1:5432/sonarjhipster
      sonar.search.javaOpts: -Xms1024m -Xmx1024m
    volumes:
      - ./sqData:/opt/sonarqube/data
      - ./sqExtensions:/opt/sonarqube/extensions
      - ./sqLogs:/opt/sonarqube/logs
      - ./sqConf:/opt/sonarqube/conf
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9001:9000
  db_JH:
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sonarjhipster
      POSTGRES_PASSWORD: sonarjhipster
      POSTGRES_DB: sonarjhipsterdb
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
volumes:
  sqData:
    name: sqData
  sqExtensions:
    name: sqExtensions
  sqLogs:
    name: sqLogs
  sqConf:
    name: sqConf
  postgresql:
    name: postgresql
  postgresql_data:
    name: postgresql_data
