# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDc5ZDg5ZWIzZWVmNDNmYzY2NGE1YjU0YzljNzdjMDk1NTNiNGNmMjAzNDQyZDljNDMyYTg4YjQxYTcwZmZhNWJlZTQzOTRkOTk0ZGU5N2E4YjMwMmJjZTM2ZTU3YmJhZGZhYjc0Y2I0NjVmODUxNTJiNTY2N2E4NTRmMGM1NzA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
